server:
  port: 8010
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bilibili-plus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  application:   #定义服务名称
    name: provider-user   #必须定义
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.blplus.api.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
#开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7010/eureka
  instance:
    instance-id: blplus-provider-8010                #定义微服务的名称，多个服务id不能相同
    prefer-ip-address: true                        #是否显示IP和端口
  
  
